language: java
jdk:
  - openjdk8
notification:
  email:
    recipients:
      - 1828566287@qq.com
    on_success: always
    on_failure: always

before_install:
  - pip install --user codecov

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - echo "MAVEN_OPTS='-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m'" > ~/.mavenrc
  
script:
  - mvn clean test jacoco:report

after_success:
  - codecov

branches:
  only:
    - master
    
env:
  global:
    - "MAVEN_OPTS=-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m"

addons:
  coverity_scan:
    project:
      name: "somesame/apollo"
      description: "Build submitted via Travis CI"
    notification_email: 1828566287@qq.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: master

cache:
  directories:
    - $HOME/.m2
